version: "3.8"

services:
  coupon:
    image: greenlab_coupon:dev
    container_name: greenlab_coupon
    build:
      context: ./src/coupon
      dockerfile: Dockerfile.dev
      target: base
    volumes:
      - ./src/coupon/src:/home/app/coupon/src
      - /home/app/coupon/node_modules/
    expose:
      - '3003'
    ports:
      - '3003:3003'
    environment:
      - PORT=3003
    command: npm run client:start:development
    stdin_open: true
  api:
    image: greenlab_api:dev
    container_name: greenlab_api
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src/api/src:/home/app/api/src
      - ./src/api/nodemon.json:/home/app/api/nodemon.json
    expose:
      - '5003'
    ports:
      - '5003:5003'
    environment:
      - PORT=5003
    command: npm run server:start:development
