version: "3.8"

networks:
  greenpeace:

services:
  coupon:
    image: greenpeace/coupon:prod
    container_name: greenpeace-coupon
    build:
      context: ./src/coupon
      dockerfile: Dockerfile.prod
    ports:
      - '3001:80'
    environment:
      - PORT=3001
    networks:
      - greenpeace
  # landing-downgrade:
  #   image: greenlab/landing-downgrade:prod
  #   container_name: greenlab-landing-downgrade
  #   build:
  #     context: ./src/landing-downgrade
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - '3002:80'
  #   environment:
  #     - PORT=3002
  api:
    image: greenpeace/api:prod
    container_name: greenpeace-api
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./src/api/src:/home/app/api/src
      - ./src/api/nodemon.json:/home/app/api/nodemon.json
    expose:
      - '5001'
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
    networks:
      - greenpeace
