version: "3.8"

services:
  coupon:
    image: greenlab_coupon:prod
    container_name: greenlab_coupon_prod
    build:
      context: ./src/coupon
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./src/coupon/src:/home/app/coupon/src
      - /home/app/coupon/node_modules/
    expose:
      - '3001'
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
  api:
    image: greenlab_api:prod
    container_name: greenlab_api
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./src/api/src:/home/app/api/src
      - ./src/api/nodemon.json:/home/app/api/nodemon.json
    expose:
      - '5001'
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
    # command: npm run server:start:watch
    # depends_on:
    #   - mongo
  # mongo:
  #   container_name: greenpeace_greenlab_mongo
  #   image: mongo:4
  #   restart: always
  #   volumes:
  #     - ./shared_volume/db/:/data/db/
  #   ports:
  #     - "27016:27017"
