version: "3.8"

services:
  coupon:
    image: greenlab_coupon:test
    container_name: greenlab_coupon
    build:
      context: ./src/coupon
      dockerfile: Dockerfile.test
    ports:
      - '3002:80'
    environment:
      - PORT=3002
  api:
    image: greenlab_api:test
    container_name: greenlab_api
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./src/api/src:/home/app/api/src
      - ./src/api/nodemon.json:/home/app/api/nodemon.json
    expose:
      - '5002'
    ports:
      - '5002:5002'
    environment:
      - PORT=5002
