version: "3.8"

services:
  coupon:
    image: greenlab_coupon:prod
    container_name: greenlab_coupon
    build:
      context: ./src/coupon
      dockerfile: Dockerfile.prod
    ports:
      - '3001:80'
    environment:
      - PORT=3001
  landing-downgrade:
    image: greenlab-landing-downgrade:prod
    container_name: greenlab-landing-downgrade
    build:
      context: ./src/landing-downgrade
      dockerfile: Dockerfile.prod
    ports:
      - '3002:80'
    environment:
      - PORT=3002
  api:
    image: greenlab_api:prod
    container_name: greenlab_api
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./src/api/src:/home/app/api/src
      - ./src/api/nodemon.json:/home/app/api/nodemon.json
    expose:
      - '5001'
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
