version: "3.8"

services:
  coupon:
    image: greenpeace/coupon:dev
    container_name: greenpeace-coupon
    build:
      context: ./src/coupon
      dockerfile: Dockerfile.dev
      target: base
    volumes:
      - ./src/coupon/src:/home/app/coupon/src
      - /home/app/coupon/node_modules/
    expose:
      - '3001'
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    command: npm run client:start:development
    stdin_open: true
  # landing-downgrade:
  #   image: greenlab/landing-downgrade:dev
  #   container_name: greenlab-landing-downgrade
  #   build:
  #     context: ./src/landing-downgrade
  #     dockerfile: Dockerfile.dev
  #     target: base
  #   volumes:
  #     - ./src/landing-downgrade/src:/home/app/landing-downgrade/src
  #     - /home/app/landing-downgrade/node_modules/
  #   expose:
  #     - '3002'
  #   ports:
  #     - '3002:3002'
  #   environment:
  #     - PORT=3002
  #   command: npm run client:start:development
  #   stdin_open: true
  api:
    image: greenpeace/api:dev
    container_name: greenpeace-api
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src/api/src:/home/app/api/src
      - ./src/api/nodemon.json:/home/app/api/nodemon.json
    expose:
      - '5003'
    ports:
      - '5003:5003'
    environment:
      - PORT=5003
    command: npm run server:start:development
