version: "3.7"

services:
  coupon:
    container_name: greenpeace_mercadopago_coupon
    image: greenpeace_mercadopago_coupon:prod
    build:
      context: ./src/coupon
      dockerfile: Dockerfile
      target: production
  api:
    container_name: greenpeace_greenlab_api
    image: greenpeace_greenlab_api:prod
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: production
