version: "3.9"

networks:
  greenpeace:

services:
  coupon:
    image: greenpeace/coupon:dev
    container_name: greenpeace-coupon
    build:
      context: ./src/coupon
      dockerfile: Dockerfile.dev
      target: base
    volumes:
      - ./src/coupon/src:/home/app/coupon/src
      - /home/app/coupon/node_modules/
    expose:
      - '3001'
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    command: npm run client:start:development
    stdin_open: true
    networks:
      - greenpeace

  # landing-downgrade:
  #   image: greenlab/landing-downgrade:dev
  #   container_name: greenlab-landing-downgrade
  #   build:
  #     context: ./src/landing-downgrade
  #     dockerfile: Dockerfile.dev
  #     target: base
  #   volumes:
  #     - ./src/landing-downgrade/src:/home/app/landing-downgrade/src
  #     - /home/app/landing-downgrade/node_modules/
  #   expose:
  #     - '3002'
  #   ports:
  #     - '3002:3002'
  #   environment:
  #     - PORT=3002
  #   command: npm run client:start:development
  #   stdin_open: true

  api:
    image: greenpeace/api:dev
    container_name: greenpeace-api
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src/api/src:/home/app/api/src
      - ./src/api/nodemon.json:/home/app/api/nodemon.json
    expose:
      - $SERVER_DOCKER_PORT
    ports:
      - $SERVER_LOCAL_PORT:$SERVER_DOCKER_PORT
    environment:
      - SERVER_PORT=$SERVER_DOCKER_PORT
      - DB_HOST=$MONGO_HOST
      - DB_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - DB_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - DB_NAME=$MONGO_DATABASE
      - DB_PORT=$MONGO_DOCKER_PORT
    command: npm run server:start:development
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - greenpeace

  mongodb:
    image: greenpeace/mongodb:dev
    container_name: $MONGO_HOST
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongodb-data:/data/db/
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - ${MONGO_LOCAL_PORT}:${MONGO_DOCKER_PORT}
    command: [--auth]
    networks:
      - greenpeace

volumes:
    mongodb-data:
      name: "greenpeace-mongodb-data-dev"
