version: "3.8"

services:
  coupon:
    image: greenlab/coupon:test
    container_name: greenlab-coupon
    build:
      context: ./src/coupon
      dockerfile: Dockerfile.test
    ports:
      - '3002:80'
    environment:
      - PORT=3002
  # landing-downgrade:
  #   image: greenlab/landing-downgrade:test
  #   container_name: greenlab-landing-downgrade
  #   build:
  #     context: ./src/landing-downgrade
  #     dockerfile: Dockerfile.test
  #   ports:
  #     - '3003:80'
  #   environment:
  #     - PORT=3003
  api:
    image: greenlab/api:test
    container_name: greenlab-api
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./src/api/src:/home/app/api/src
      - ./src/api/nodemon.json:/home/app/api/nodemon.json
    expose:
      - '5002'
    ports:
      - '5002:5002'
    environment:
      - PORT=5002
