version: "3.7"

services:
  coupon:
    image: greenpeace_mercadopago_coupon:dev
    container_name: greenpeace_mercadopago_coupon
    build:
      context: ./src/coupon
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src/coupon/src:/home/app/coupon/src
      - /home/app/coupon/node_modules/
    expose:
      - '3001'
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    command: npm run client:start:development
    stdin_open: true
  api:
    image: greenpeace_greenlab_api:dev
    container_name: greenpeace_greenlab_api
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src/api/src:/home/app/api/src
      - ./src/api/nodemon.json:/home/app/api/nodemon.json
    expose:
      - '5001'
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
    command: npm run start:dev
    # depends_on:
    #   - mongo
  # mongo:
  #   container_name: greenpeace_greenlab_mongo
  #   image: mongo:4
  #   restart: always
  #   volumes:
  #     - ./shared_volume/db/:/data/db/
  #   ports:
  #     - "27016:27017"
